### ISSUE TITLE
Descrizione Problema

### ISSUE THREAD

**Issue by lucifero55** [lucifero55/guess#1]

**Comment by FabioZTessitore** [comment]
![es5_35](https://cloud.githubusercontent.com/assets/3002194/18102703/cd670710-6ef3-11e6-8e21-1074777c70c3.png)

**Comment by FabioZTessitore** [comment]
Ho inserito dei commenti nel codice per segnalare i problemi.
Fai un git pull per scaricare

**Comment by FabioZTessitore** [comment]
ok

ps. random_between(a, b) estrae numeri compresi tra a e b. a incluso e b escluso. (va bene così, non cambiarla). Quindi random_between(1, 1000) estrae numeri compresi tra 1 e 999.
puoi creare un test_random.c ed estrarre 100 numeri compresi tra 0 e 2 e contare quante volte esce 0, quante 1 e quante 2 (il 2 deve uscire 0 volte ovviamente)
