### ISSUE TITLE
Contatore tentativi

### ISSUE THREAD

**Issue by FabioZTessitore** [lucifero55/guess#2]
![es5_36](https://cloud.githubusercontent.com/assets/3002194/18127251/773e1612-6f7f-11e6-9339-0d7cd76ab4f3.png)

**Comment by lucifero55** [comment]
Ma se quando è inferiore o uguale deve stampare un ipotetico "HaiAvutoCulo()"
E quando ne fa 10 deve stampare un ipotetico "Bravo()"
Quando ne farà 10 non li stamperà entrambi?

**Comment by FabioZTessitore** [comment]
Il testo non è molto chiaro quindi puoi fare come credi

**Comment by lucifero55** [comment]
come va?

**Comment by lucifero55** [comment]
Da oggi pomeriggio sarò inattivo fino a domenica per vacanza

**Comment by FabioZTessitore** [comment]
in massima parte bene. Le cose che non mi convincono sono 2:

1) continui ad estrarre numeri tra 1 e 999 perché 1000 è escluso (sei testardo)
2) (più importante) riguarda la scelta degli estremi 1 e 1000. Questi numeri sono definiti nel main e correttamente li passi alla funzione di guess che stampa il messaggio iniziale. Però la funzione di guess che estrae il numero non li prende come parametri.
In altre parole, da una parte il modulo guess non conosce minimo e massimo e devi dirglielo tu, dall'altra invece li conosce e fa a modo suo. Questa è una incoerenza. O in un modo o nell'altro.
Io preferisco passare minimo e massimo come hai fatto con il messaggio iniziale così se decidi di cambiare lo fai nel main e tutto funziona bene

**Comment by lucifero55** [comment]
Non l'ho cambiata perchè mi avevate detto di non farlo :c 
![schermata del 2016-09-01 11-58-09](https://cloud.githubusercontent.com/assets/16176113/18163474/74017b94-703b-11e6-934a-de10a20df4af.png)

**Comment by FabioZTessitore** [comment]
random_between non va cambiata
